services:
  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=https://safewalku.online/api
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=safewalku
